services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/skurt/Desktop/mariadb # To change on 42 device
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/skurt/Desktop/wordpress # To change on 42 device

networks:
  inception:
    driver: bridge
